function [car_motion_struct] = get_car_straight_motion_param_struct(x, y, v, phi, acc_tan, time_grid)

      field_names = get_field_names();

      car_motion_struct = struct(field_names.x, x, ...
                                field_names.y, y, ...
                                field_names.v, v, ...
                                field_names.phi, phi, ...
                                field_names.acc_tan, acc_tan, ...
                                field_names.t, time_grid);

end