function d_x_y_vx_vy_phi = straight_motion_eq(t, x_y_vx_vy_phi, v_0, sign_acc)

    v = v_0 + sign_acc * t;
    phi = x_y_vx_vy_phi(5);

    d_x_y_vx_vy_phi = [ ...
        v * sin(phi); ...
        v * cos(phi); ...
        sign_acc * sin(phi); ...
        sign_acc * cos(phi); ...
        0 ...
    ];

end